contracts_folder: ./contracts/
hardhat:
  host: 127.0.0.1:8545

plugins:
  - name: hardhat
  - name: solidity

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.5.0
